-- Sankhuu: туршилтын (demo) 3 дэлгүүр, 18 бараа, 12 үнэлгээ. Supabase SQL Editor-т нэг удаа ажиллуулна.
-- Устгах бол demo-cleanup.sql. Бүх id 'demo_' угтвартай тул бодит өгөгдөлд хүрэхгүй.

BEGIN;
SET LOCAL search_path TO public;

INSERT INTO public."Address"(id,district,khoroo,details) VALUES ('demo_a1','Сүхбаатар','1','Их сургуулийн гудамж 12, 3-р орц, 405 тоот');
INSERT INTO public."Shop"(id,name,slug,phone,"isActive","createdAt","updatedAt","pickupAddressId") VALUES ('demo_s1','Сарнай Бутик','demo-sarnai-butik','+97699110001',true,now()-interval '30 days',now(),'demo_a1');
INSERT INTO public."Address"(id,district,khoroo,details) VALUES ('demo_a2','Баянгол','14','Энхтайвны өргөн чөлөө 45, 2-р орц, 301 тоот');
INSERT INTO public."Shop"(id,name,slug,phone,"isActive","createdAt","updatedAt","pickupAddressId") VALUES ('demo_s2','Номин Гоо Сайхан','demo-nomin-goo','+97699110002',true,now()-interval '30 days',now(),'demo_a2');
INSERT INTO public."Address"(id,district,khoroo,details) VALUES ('demo_a3','Хан-Уул','11','Зайсан, Нарны зам 8, 1 давхар');
INSERT INTO public."Shop"(id,name,slug,phone,"isActive","createdAt","updatedAt","pickupAddressId") VALUES ('demo_s3','Техно Плаза','demo-techno-plaza','+97699110003',true,now()-interval '30 days',now(),'demo_a3');

INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p01','demo_s1','Цагаан хөвөн футболк, унисекс',39000,NULL,25,'Хувцас','100% хөвөн, зузаан даавуутай. S–XXL размертай. Угаахад суухгүй.',ARRAY['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '1 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p02','demo_s1','Эмэгтэй урт даашинз, зуны',129000,169000,6,'Хувцас','Хөнгөн даавуутай, уян хатан. S, M, L размертай. Дагалдах бүстэй.',ARRAY['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '2 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p03','demo_s1','Саарал ноосон свитер',95000,NULL,12,'Хувцас','Мерино ноосон холимог, зөөлөн, дулаан. Өвлийн улиралд тохиромжтой.',ARRAY['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '3 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p04','demo_s1','Хар арьсан цүнх',185000,230000,3,'Цүнх, аксессуар','Жинхэнэ арьс, мөрний тохируулгатай оосор, дотор 3 хэсэгтэй.',ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '5 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p05','demo_s1','Нарны шил, алтан хүрээтэй',65000,NULL,9,'Цүнх, аксессуар','UV400 хамгаалалттай, хайрцаг дагалдана.',ARRAY['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '6 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p06','demo_s1','Улаан пүүз, спорт загвар',210000,260000,4,'Гутал','Хөнгөн, амьсгалдаг материал. 36–44 размер.',ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1560343090-f0409e92791a?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '4 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p07','demo_s1','Цагаан пүүз, өдөр тутмын',145000,NULL,8,'Гутал','Сонгодог загвар, ямар ч хувцастай зохицно. 36–43 размер.',ARRAY['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '9 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p08','demo_s2','Уруулын будаг, матт улаан',28000,35000,30,'Гоо сайхан','12 цаг тогтоцтой, хуурайшуулахгүй чийгшүүлэгчтэй. 6 өнгөтэй.',ARRAY['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '1 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p09','demo_s2','Нүүрний тос, гиалуроны хүчилтэй 50мл',48000,NULL,20,'Гоо сайхан','Бүх төрлийн арьсанд. Өглөө, орой хэрэглэнэ. Үнэргүй.',ARRAY['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '2 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p10','demo_s2','Нүдний будгийн палитр, 12 өнгө',56000,72000,10,'Гоо сайхан','Гялгар ба матт өнгөнүүд хосолсон. Удаан тогтоно.',ARRAY['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '7 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p11','demo_s2','Эмэгтэй сүрчиг 50мл',139000,NULL,5,'Гоо сайхан','Цэцэгс, жимсний үнэртэй, өдрийн хэрэглээнд. Бэлгийн хайрцагтай.',ARRAY['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '3 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p12','demo_s2','Анхилуун лаа, ванилийн',24000,NULL,15,'Гэр ахуй','Соёолжны лав, 40 цаг шатна. Шилэн саванд.',ARRAY['https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '8 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p13','demo_s3','Утасгүй чихэвч, дуу тусгаарлагчтай',189000,249000,7,'Электрон бараа','Bluetooth 5.3, идэвхтэй дуу тусгаарлалт, 30 цаг ажиллана. Хайрцаг, кабель дагалдана.',ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1583394838336-acd977736f90?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '1 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p14','demo_s3','Ухаалаг цаг, зүрхний цохилт хэмжигчтэй',159000,NULL,11,'Электрон бараа','1.8" дэлгэц, 7 хоног цэнэг барина, усны хамгаалалттай. Android/iOS.',ARRAY['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=900&q=80&auto=format&fit=crop','https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '2 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p15','demo_s3','Утасны хамгаалалтын хайрцаг, тунгалаг',15000,NULL,40,'Электрон бараа','Цохилт тэсвэрлэдэг, шарлахгүй материал. iPhone 13–16 загварт.',ARRAY['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '4 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p16','demo_s3','Гэрийн дасгалын дэвсгэр 6мм',45000,60000,14,'Спорт','Гулсдаггүй, 183×61 см, зөөвөрлөх оосортой.',ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '5 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p17','demo_s3','Хүүхдийн тоглоом, зөөлөн баавгай 40см',32000,NULL,18,'Хүүхдийн бараа','Аюулгүй, угааж болно. 0+ насны хүүхдэд.',ARRAY['https://images.unsplash.com/photo-1522771930-78848d9293e8?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '6 days',now());
INSERT INTO public."Product"(id,"shopId",name,price,"compareAtPrice",stock,category,description,images,"isActive","createdAt","updatedAt") VALUES ('demo_p18','demo_s3','Хүүхдийн өвлийн комбинзон',89000,110000,0,'Хүүхдийн бараа','Дулаан, ус нэвтрүүлдэггүй. 2–6 нас.',ARRAY['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&q=80&auto=format&fit=crop']::text[],true,now()-interval '10 days',now());

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c01','demo_s1','Болормаа','+97688000001',now()-interval '5 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad01','demo_c01','Баянзүрх','5','Туршилтын хаяг 1');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o01','demo_s1','demo_c01','OTHER','DELIVERED',39000,5000,44000,'CASH_ON_DELIVERY','PAID',now()-interval '5 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o01_i','demo_o01','demo_p01','Цагаан хөвөн футболк, унисекс',39000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d01','demo_o01','DELIVERED','demo_a1','demo_ad01',5000,44000,44000,now()-interval '4 days',now()-interval '5 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r01','demo_p01','demo_o01','demo_s1',5,'Даавуу нь зузаан, хэмжээ яг таарсан. Хоёр дахь удаагаа авч байна.','{}','Болормаа',now()-interval '3 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c02','demo_s1','Тэмүүлэн','+97688000002',now()-interval '8 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad02','demo_c02','Баянзүрх','5','Туршилтын хаяг 2');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o02','demo_s1','demo_c02','OTHER','DELIVERED',39000,5000,44000,'CASH_ON_DELIVERY','PAID',now()-interval '8 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o02_i','demo_o02','demo_p01','Цагаан хөвөн футболк, унисекс',39000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d02','demo_o02','DELIVERED','demo_a1','demo_ad02',5000,44000,44000,now()-interval '7 days',now()-interval '8 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r02','demo_p01','demo_o02','demo_s1',4,'Сайн чанартай. Цагаан өнгө нь бага зэрэг тунгалаг.','{}','Тэмүүлэн',now()-interval '6 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c03','demo_s1','Сарангэрэл','+97688000003',now()-interval '6 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad03','demo_c03','Баянзүрх','5','Туршилтын хаяг 3');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o03','demo_s1','demo_c03','OTHER','DELIVERED',129000,5000,134000,'CASH_ON_DELIVERY','PAID',now()-interval '6 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o03_i','demo_o03','demo_p02','Эмэгтэй урт даашинз, зуны',129000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d03','demo_o03','DELIVERED','demo_a1','demo_ad03',5000,134000,134000,now()-interval '5 days',now()-interval '6 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r03','demo_p02','demo_o03','demo_s1',5,'Зурган дээрхтэй яг адилхан. Хүргэлт маргааш нь ирсэн.','{}','Сарангэрэл',now()-interval '4 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c04','demo_s1','Оюунаа','+97688000004',now()-interval '10 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad04','demo_c04','Баянзүрх','5','Туршилтын хаяг 4');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o04','demo_s1','demo_c04','OTHER','DELIVERED',185000,5000,190000,'CASH_ON_DELIVERY','PAID',now()-interval '10 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o04_i','demo_o04','demo_p04','Хар арьсан цүнх',185000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d04','demo_o04','DELIVERED','demo_a1','demo_ad04',5000,190000,190000,now()-interval '9 days',now()-interval '10 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r04','demo_p04','demo_o04','demo_s1',5,'Арьс нь жинхэнэ, үнэр нь сайхан. Үнэ цэнээрээ маш сайн.','{}','Оюунаа',now()-interval '8 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c05','demo_s1','Батбаяр','+97688000005',now()-interval '7 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad05','demo_c05','Баянзүрх','5','Туршилтын хаяг 5');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o05','demo_s1','demo_c05','OTHER','DELIVERED',210000,5000,215000,'CASH_ON_DELIVERY','PAID',now()-interval '7 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o05_i','demo_o05','demo_p06','Улаан пүүз, спорт загвар',210000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d05','demo_o05','DELIVERED','demo_a1','demo_ad05',5000,215000,215000,now()-interval '6 days',now()-interval '7 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r05','demo_p06','demo_o05','demo_s1',4,'Хөнгөн, хөл эвгүйрдэггүй. Размер нэгээр том захиалаарай.','{}','Батбаяр',now()-interval '5 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c06','demo_s2','Номин','+97688000006',now()-interval '4 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad06','demo_c06','Баянзүрх','5','Туршилтын хаяг 6');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o06','demo_s2','demo_c06','OTHER','DELIVERED',28000,5000,33000,'CASH_ON_DELIVERY','PAID',now()-interval '4 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o06_i','demo_o06','demo_p08','Уруулын будаг, матт улаан',28000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d06','demo_o06','DELIVERED','demo_a2','demo_ad06',5000,33000,33000,now()-interval '3 days',now()-interval '4 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r06','demo_p08','demo_o06','demo_s2',5,'Өнгө нь гоё, удаан тогтдог. Найзууддаа бэлэглэсэн.','{}','Номин',now()-interval '2 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c07','demo_s2','Ариунаа','+97688000007',now()-interval '11 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad07','demo_c07','Баянзүрх','5','Туршилтын хаяг 7');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o07','demo_s2','demo_c07','OTHER','DELIVERED',28000,5000,33000,'CASH_ON_DELIVERY','PAID',now()-interval '11 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o07_i','demo_o07','demo_p08','Уруулын будаг, матт улаан',28000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d07','demo_o07','DELIVERED','demo_a2','demo_ad07',5000,33000,33000,now()-interval '10 days',now()-interval '11 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r07','demo_p08','demo_o07','demo_s2',5,'Матт боловч уруул хуурайшуулдаггүй.','{}','Ариунаа',now()-interval '9 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c08','demo_s2','Мөнхзул','+97688000008',now()-interval '9 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad08','demo_c08','Баянзүрх','5','Туршилтын хаяг 8');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o08','demo_s2','demo_c08','OTHER','DELIVERED',48000,5000,53000,'CASH_ON_DELIVERY','PAID',now()-interval '9 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o08_i','demo_o08','demo_p09','Нүүрний тос, гиалуроны хүчилтэй 50мл',48000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d08','demo_o08','DELIVERED','demo_a2','demo_ad08',5000,53000,53000,now()-interval '8 days',now()-interval '9 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r08','demo_p09','demo_o08','demo_s2',4,'Арьс чийглэг болсон. Үнэргүй нь таалагдсан.','{}','Мөнхзул',now()-interval '7 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c09','demo_s3','Ганбат','+97688000009',now()-interval '5 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad09','demo_c09','Баянзүрх','5','Туршилтын хаяг 9');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o09','demo_s3','demo_c09','OTHER','DELIVERED',189000,5000,194000,'CASH_ON_DELIVERY','PAID',now()-interval '5 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o09_i','demo_o09','demo_p13','Утасгүй чихэвч, дуу тусгаарлагчтай',189000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d09','demo_o09','DELIVERED','demo_a3','demo_ad09',5000,194000,194000,now()-interval '4 days',now()-interval '5 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r09','demo_p13','demo_o09','demo_s3',5,'Дуу тусгаарлалт нь гайхалтай. Автобусанд ч чимээгүй.','{}','Ганбат',now()-interval '3 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c10','demo_s3','Энхжин','+97688000010',now()-interval '13 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad10','demo_c10','Баянзүрх','5','Туршилтын хаяг 10');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o10','demo_s3','demo_c10','OTHER','DELIVERED',189000,5000,194000,'CASH_ON_DELIVERY','PAID',now()-interval '13 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o10_i','demo_o10','demo_p13','Утасгүй чихэвч, дуу тусгаарлагчтай',189000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d10','demo_o10','DELIVERED','demo_a3','demo_ad10',5000,194000,194000,now()-interval '12 days',now()-interval '13 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r10','demo_p13','demo_o10','demo_s3',4,'Дуу сайн, батарей удаан. Чихэнд жаахан том.','{}','Энхжин',now()-interval '11 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c11','demo_s3','Дөлгөөн','+97688000011',now()-interval '8 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad11','demo_c11','Баянзүрх','5','Туршилтын хаяг 11');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o11','demo_s3','demo_c11','OTHER','DELIVERED',159000,5000,164000,'CASH_ON_DELIVERY','PAID',now()-interval '8 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o11_i','demo_o11','demo_p14','Ухаалаг цаг, зүрхний цохилт хэмжигчтэй',159000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d11','demo_o11','DELIVERED','demo_a3','demo_ad11',5000,164000,164000,now()-interval '7 days',now()-interval '8 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r11','demo_p14','demo_o11','demo_s3',5,'Утастай амархан холбогдсон, алхам, нойр хэмждэг.','{}','Дөлгөөн',now()-interval '6 days');

INSERT INTO public."Customer"(id,"shopId",name,phone,"createdAt","updatedAt") VALUES ('demo_c12','demo_s3','Сүхээ','+97688000012',now()-interval '6 days',now()) ON CONFLICT DO NOTHING;
INSERT INTO public."Address"(id,"customerId",district,khoroo,details) VALUES ('demo_ad12','demo_c12','Баянзүрх','5','Туршилтын хаяг 12');
INSERT INTO public."Order"(id,"shopId","customerId",source,status,subtotal,"deliveryFee",total,"paymentMethod","paymentStatus","createdAt","updatedAt") VALUES ('demo_o12','demo_s3','demo_c12','OTHER','DELIVERED',45000,5000,50000,'CASH_ON_DELIVERY','PAID',now()-interval '6 days',now());
INSERT INTO public."OrderItem"(id,"orderId","productId",name,"unitPrice",quantity) VALUES ('demo_o12_i','demo_o12','demo_p16','Гэрийн дасгалын дэвсгэр 6мм',45000,1);
INSERT INTO public."Delivery"(id,"orderId",status,"pickupAddressId","dropoffAddressId",fee,"codAmount","codCollected","deliveredAt","createdAt","updatedAt") VALUES ('demo_d12','demo_o12','DELIVERED','demo_a3','demo_ad12',5000,50000,50000,now()-interval '5 days',now()-interval '6 days',now());
INSERT INTO public."Review"(id,"productId","orderId","shopId",rating,comment,images,"customerName","createdAt") VALUES ('demo_r12','demo_p16','demo_o12','demo_s3',5,'Гулсдаггүй, зузаан. Йогад тохиромжтой.','{}','Сүхээ',now()-interval '4 days');

-- Барааны үнэлгээний тоологчийг тооцно
UPDATE public."Product" p SET "ratingCount"=r.c, "ratingSum"=r.s FROM (SELECT "productId", count(*) c, sum(rating) s FROM "Review" WHERE id LIKE 'demo_%' GROUP BY 1) r WHERE p.id=r."productId";

COMMIT;
